logging:
  level:
    org:
      springframework:
        security: trace
server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          auth:
            converter:
              resourceId: cashcard-api
              principal-attributes: preferred_username
          issuer-uri: http://localhost:8080/realms/spring-auth
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
